# Based on https://github.com/scyto/infinitude/blob/master/.github/workflows/docker-buildx-pushto-dockerhub.yml

name: Docker Buildx

on:
  push:
    branches: 
    - master
  workflow_dispatch:
  
jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: linux/amd64,linux/arm64 #architectures

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest

      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Available_platforms 
        run: echo ${{ steps.buildx.outputs.platforms }} #this is for logging

      - name: Builder instance name
        run: echo ${{ steps.buildx.outputs.name }} #this is for logging

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          platforms: ${{ steps.buildx.outputs.platforms }} #this builds one tag per architecture platforms you specified in the set up QEMU.
          tags: ghcr.io/gar-syn/blocktopus:latest #set to the github repo this will be pushed to

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }} #this is for logging.
        
